name: ${project.name}
main: com.beecub.bLog.bLog
url: ${project.url}
version: ${project.version}
author: beecub,morganm
description: >
             Logger
commands:
  bLog:
    description: reload config
    usage: |
           /<command> [reload]
